on: [push]
env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
  NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}
jobs:
  ls:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd ${{ github.workspace }}
          nix-build
          neocities push --prune result